spring:
  cloud:
    gateway:
      routes:
        - id: product_router
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: admin_router
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}


    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gateway
server:
  port: 88
